from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
import io
from datetime import datetime
from app.logger import get_logger

logger = get_logger(__name__)

def generate_client_report(
    client: dict,
    analysis: dict
) -> bytes:
    """Generate a professional Word document for a client"""
    doc = Document()

    # Page margins
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1.2)
        section.right_margin = Inches(1.2)

    # Title
    title = doc.add_heading("Client Intake Report", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Subtitle
    subtitle = doc.add_paragraph(
        f"Generated: {datetime.now().strftime('%B %d, %Y %I:%M %p')}"
    )
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph()

    # Client Details Section
    doc.add_heading("Client Details", level=1)

    table = doc.add_table(rows=0, cols=2)
    table.style = "Table Grid"
    table.alignment = WD_TABLE_ALIGNMENT.LEFT

    fields = [
        ("Client ID", client.get("client_id", "N/A")),
        ("Name", client.get("name", "N/A")),
        ("Company", client.get("company") or "Not provided"),
        ("Email", client.get("email") or "Not provided"),
        ("Phone", client.get("phone") or "Not provided"),
        ("Service", client.get("service") or "Not provided"),
        ("Priority", client.get("priority", "Medium")),
        ("Stage", client.get("stage", "New")),
        ("Created", client.get("created_at", "N/A")[:10]),
    ]

    for label, value in fields:
        row = table.add_row().cells
        row[0].text = label
        row[1].text = str(value)
        row[0].paragraphs[0].runs[0].bold = True

    doc.add_paragraph()

    # Executive Summary
    if analysis.get("executive_summary"):
        doc.add_heading("Executive Summary", level=1)
        doc.add_paragraph(analysis["executive_summary"])
        doc.add_paragraph()

    # Business Problem
    if analysis.get("business_problem"):
        doc.add_heading("Business Problem", level=1)
        doc.add_paragraph(analysis["business_problem"])
        doc.add_paragraph()

    # Current Process
    if analysis.get("current_process"):
        doc.add_heading("Current Process", level=1)
        doc.add_paragraph(analysis["current_process"])
        doc.add_paragraph()

    # Recommendations
    if analysis.get("recommendations"):
        doc.add_heading("Recommendations", level=1)
        for i, rec in enumerate(analysis["recommendations"], 1):
            doc.add_paragraph(
                f"{i}. {rec}",
                style="List Number"
            )
        doc.add_paragraph()

    # Open Questions
    if analysis.get("open_questions"):
        doc.add_heading("Open Questions", level=1)
        for q in analysis["open_questions"]:
            doc.add_paragraph(f"• {q}")
        doc.add_paragraph()

    # Additional Notes
    if analysis.get("notes") or client.get("notes"):
        doc.add_heading("Additional Notes", level=1)
        doc.add_paragraph(
            analysis.get("notes") or client.get("notes", "")
        )

    # Footer
    doc.add_paragraph()
    footer_text = doc.add_paragraph(
        "This report was generated by AI CRM Agent. "
        "Please verify all information before use."
    )
    footer_text.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Save to bytes
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)

    logger.info(f"Generated report for client: {client.get('client_id')}")

    return buffer.getvalue()


def generate_pipeline_report(
    summary: dict,
    clients: list
) -> bytes:
    """Generate a pipeline summary Word document"""
    doc = Document()

    # Title
    title = doc.add_heading("Pipeline Summary Report", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    subtitle = doc.add_paragraph(
        f"Generated: {datetime.now().strftime('%B %d, %Y %I:%M %p')}"
    )
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph()

    # Overview stats
    doc.add_heading("Overview", level=1)

    stats_table = doc.add_table(rows=0, cols=2)
    stats_table.style = "Table Grid"

    stats = [
        ("Total Clients", str(summary.get("total_clients", 0))),
        ("High Priority Pending", str(summary.get("high_priority_pending_count", 0))),
    ]

    for label, value in stats:
        row = stats_table.add_row().cells
        row[0].text = label
        row[1].text = value
        row[0].paragraphs[0].runs[0].bold = True

    doc.add_paragraph()

    # Stage breakdown
    doc.add_heading("Pipeline by Stage", level=1)

    stage_table = doc.add_table(rows=0, cols=2)
    stage_table.style = "Table Grid"

    header_row = stage_table.add_row().cells
    header_row[0].text = "Stage"
    header_row[1].text = "Count"
    header_row[0].paragraphs[0].runs[0].bold = True
    header_row[1].paragraphs[0].runs[0].bold = True

    for stage, count in summary.get("stage_counts", {}).items():
        row = stage_table.add_row().cells
        row[0].text = stage
        row[1].text = str(count)

    doc.add_paragraph()

    # High priority clients
    if summary.get("high_priority_pending_clients"):
        doc.add_heading("High Priority Pending Clients", level=1)

        hp_table = doc.add_table(rows=0, cols=4)
        hp_table.style = "Table Grid"

        header = hp_table.add_row().cells
        for i, h in enumerate(["Client ID", "Name", "Company", "Stage"]):
            header[i].text = h
            header[i].paragraphs[0].runs[0].bold = True

        for c in summary["high_priority_pending_clients"]:
            row = hp_table.add_row().cells
            row[0].text = c.get("client_id", "")
            row[1].text = c.get("name", "")
            row[2].text = c.get("company", "")
            row[3].text = c.get("stage", "")

    doc.add_paragraph()

    # All clients table
    doc.add_heading("All Active Clients", level=1)

    all_table = doc.add_table(rows=0, cols=5)
    all_table.style = "Table Grid"

    header = all_table.add_row().cells
    for i, h in enumerate(["Name", "Company", "Email", "Priority", "Stage"]):
        header[i].text = h
        header[i].paragraphs[0].runs[0].bold = True

    for c in clients:
        row = all_table.add_row().cells
        row[0].text = c.get("name", "")
        row[1].text = c.get("company", "")
        row[2].text = c.get("email", "")
        row[3].text = c.get("priority", "")
        row[4].text = c.get("stage", "")

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)

    logger.info("Generated pipeline summary report")

    return buffer.getvalue()