from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
import io
from datetime import datetime, date, timedelta
from typing import List, Optional
from app.logger import get_logger

logger = get_logger(__name__)

# ── Design constants ───────────────────────────────────
TEAL = RGBColor(0x2D, 0x7A, 0x6B)
MUTED = RGBColor(0x5A, 0x55, 0x50)
LIGHT = RGBColor(0x9A, 0x90, 0x80)


def _style_heading(para, color=TEAL):
    """Apply brand color to heading"""
    for run in para.runs:
        run.font.color.rgb = color
        run.font.bold = True


def _add_table(
    doc,
    headers: list,
    rows: list,
    col_widths: list = None
):
    """
    Add a styled table. Handles empty runs gracefully.
    col_widths in inches, optional.
    """
    if not rows:
        doc.add_paragraph("No data available.")
        doc.add_paragraph()
        return None

    table = doc.add_table(rows=0, cols=len(headers))
    table.style = "Table Grid"

    # Header row
    hdr = table.add_row().cells
    for i, h in enumerate(headers):
        hdr[i].text = str(h)
        runs = hdr[i].paragraphs[0].runs
        if runs:
            runs[0].bold = True
            runs[0].font.color.rgb = TEAL

    # Data rows
    for row_data in rows:
        row = table.add_row().cells
        for i, val in enumerate(row_data):
            if i < len(row):
                row[i].text = str(val) if val is not None else ""

    doc.add_paragraph()
    return table


def _add_section(doc, title: str, content: str):
    """Add a styled heading + paragraph"""
    h = doc.add_heading(title, level=1)
    _style_heading(h)
    doc.add_paragraph(content)
    doc.add_paragraph()


def _doc_setup(doc) -> None:
    """Set standard page margins"""
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1.25)
        section.right_margin = Inches(1.25)


def _doc_title(doc, title: str, subtitle: str) -> None:
    """Add branded title and subtitle"""
    t = doc.add_heading(title, 0)
    t.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _style_heading(t, TEAL)

    sub = doc.add_paragraph(subtitle)
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    if sub.runs:
        sub.runs[0].italic = True
        sub.runs[0].font.color.rgb = LIGHT
    doc.add_paragraph()


def _doc_footer(doc) -> None:
    """Add standard branded footer"""
    doc.add_paragraph()
    footer = doc.add_paragraph(
        "Generated by ARIA AI CRM — "
        "Please verify all information before use."
    )
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    if footer.runs:
        footer.runs[0].italic = True
        footer.runs[0].font.size = Pt(9)
        footer.runs[0].font.color.rgb = LIGHT


def _to_bytes(doc) -> bytes:
    """Save document to bytes"""
    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.getvalue()


# ── Reports ────────────────────────────────────────────

def generate_weekly_report(
    clients: List[dict],
    activities: List[dict],
    pipeline_summary: dict,
    week_start: Optional[str] = None,
    week_end: Optional[str] = None
) -> bytes:
    """Generate weekly performance report"""
    doc = Document()
    _doc_setup(doc)

    if not week_start:
        today = date.today()
        monday = today - timedelta(days=today.weekday())
        week_start = monday.strftime("%B %d, %Y")
        week_end = (
            monday + timedelta(days=6)
        ).strftime("%B %d, %Y")

    _doc_title(
        doc,
        "WEEKLY PERFORMANCE REPORT",
        f"Week of {week_start} — {week_end}\n"
        f"Generated: "
        f"{datetime.now().strftime('%B %d, %Y %I:%M %p')}"
    )

    # Key metrics
    h = doc.add_heading("KEY METRICS", level=1)
    _style_heading(h)

    won = sum(
        1 for c in clients if c.get("stage") == "Won"
    )
    lost = sum(
        1 for c in clients if c.get("stage") == "Lost"
    )
    new_count = sum(
        1 for c in clients if c.get("stage") == "New"
    )
    high_pri = sum(
        1 for c in clients
        if c.get("priority") == "High"
        and c.get("stage") not in ("Won", "Lost")
    )
    win_rate = (
        f"{round(won / (won + lost) * 100)}%"
        if (won + lost) > 0 else "N/A"
    )
    success_acts = sum(
        1 for a in activities
        if a.get("result") == "SUCCESS"
    )

    _add_table(doc,
        ["Metric", "Value"],
        [
            ["Total Clients",
             str(pipeline_summary.get(
                 "total_clients", 0
             ))],
            ["New Clients", str(new_count)],
            ["Deals Won", str(won)],
            ["Deals Lost", str(lost)],
            ["Win Rate", win_rate],
            ["High Priority Pending", str(high_pri)],
            ["Total Activities", str(len(activities))],
            ["Successful Activities", str(success_acts)]
        ]
    )

    # Pipeline breakdown
    h = doc.add_heading("PIPELINE BREAKDOWN", level=1)
    _style_heading(h)
    total = pipeline_summary.get("total_clients", 1) or 1
    _add_table(doc,
        ["Stage", "Count", "%"],
        [
            [
                stage,
                str(count),
                f"{round(count / total * 100, 1)}%"
            ]
            for stage, count in
            pipeline_summary.get("stage_counts", {}).items()
        ]
    )

    # Activity type breakdown
    h = doc.add_heading("ACTIVITY BREAKDOWN", level=1)
    _style_heading(h)
    activity_types: dict = {}
    for a in activities:
        t = a.get("type", "UNKNOWN")
        activity_types[t] = activity_types.get(t, 0) + 1

    _add_table(doc,
        ["Activity Type", "Count"],
        sorted(
            [[t, str(c)]
             for t, c in activity_types.items()],
            key=lambda x: int(x[1]),
            reverse=True
        )
    )

    # High priority clients
    h = doc.add_heading("HIGH PRIORITY CLIENTS", level=1)
    _style_heading(h)
    hp_clients = [
        c for c in clients
        if c.get("priority") == "High"
        and c.get("stage") not in ("Won", "Lost")
    ]
    _add_table(doc,
        ["Name", "Company", "Stage", "Next Follow-up"],
        [
            [
                c.get("name", ""),
                c.get("company", ""),
                c.get("stage", ""),
                c.get("next_follow_up", "Not set")
            ]
            for c in hp_clients
        ]
    )

    # Recent activities
    h = doc.add_heading("RECENT ACTIVITIES", level=1)
    _style_heading(h)
    _add_table(doc,
        ["Timestamp", "Client", "Type", "Result"],
        [
            [
                str(a.get("timestamp", ""))[:16],
                a.get("client_id", ""),
                a.get("type", ""),
                a.get("result", "")
            ]
            for a in activities[:20]
        ]
    )

    _doc_footer(doc)
    logger.info("Weekly report generated")
    return _to_bytes(doc)


def generate_monthly_report(
    clients: List[dict],
    activities: List[dict],
    pipeline_summary: dict,
    month: Optional[str] = None
) -> bytes:
    """Generate monthly pipeline report"""
    doc = Document()
    _doc_setup(doc)

    if not month:
        month = datetime.now().strftime("%B %Y")

    _doc_title(
        doc,
        "MONTHLY PIPELINE REPORT",
        f"Month: {month}\n"
        f"Generated: "
        f"{datetime.now().strftime('%B %d, %Y')}"
    )

    total = pipeline_summary.get("total_clients", 0)
    won = pipeline_summary.get("won_count", 0)
    lost = pipeline_summary.get("lost_count", 0)
    win_rate = (
        round(won / (won + lost) * 100)
        if (won + lost) > 0 else 0
    )
    hp = pipeline_summary.get(
        "high_priority_pending_count", 0
    )

    _add_section(
        doc,
        "EXECUTIVE SUMMARY",
        f"The pipeline contains {total} total clients this "
        f"month. Win rate is {win_rate}% with {won} deals won "
        f"and {lost} lost. {hp} high priority clients are "
        f"currently pending action."
    )

    # Pipeline overview with %
    h = doc.add_heading("PIPELINE OVERVIEW", level=1)
    _style_heading(h)
    _add_table(doc,
        ["Stage", "Count", "Percentage"],
        [
            [
                stage,
                str(count),
                f"{round(count / total * 100)}%"
                if total > 0 else "0%"
            ]
            for stage, count in
            pipeline_summary.get(
                "stage_counts", {}
            ).items()
        ]
    )

    # Clients by stage
    h = doc.add_heading("CLIENTS BY STAGE", level=1)
    _style_heading(h)
    stages = [
        "New", "Contacted",
        "Consultation Scheduled",
        "Proposal Sent", "Won", "Lost"
    ]
    for stage in stages:
        stage_clients = [
            c for c in clients
            if c.get("stage") == stage
        ]
        if not stage_clients:
            continue
        sub = doc.add_heading(
            f"{stage} ({len(stage_clients)})", level=2
        )
        for run in sub.runs:
            run.font.color.rgb = MUTED
        _add_table(doc,
            ["Name", "Company", "Priority", "Follow-up"],
            [
                [
                    c.get("name", ""),
                    c.get("company", ""),
                    c.get("priority", ""),
                    c.get("next_follow_up", "")
                ]
                for c in stage_clients
            ]
        )

    # Activity breakdown
    h = doc.add_heading(
        "MONTHLY ACTIVITY BREAKDOWN", level=1
    )
    _style_heading(h)
    activity_types: dict = {}
    for a in activities:
        t = a.get("type", "UNKNOWN")
        activity_types[t] = activity_types.get(t, 0) + 1

    _add_table(doc,
        ["Activity Type", "Count"],
        sorted(
            [[t, str(c)]
             for t, c in activity_types.items()],
            key=lambda x: int(x[1]),
            reverse=True
        )
    )

    _doc_footer(doc)
    logger.info("Monthly report generated")
    return _to_bytes(doc)


def generate_client_acquisition_report(
    clients: List[dict]
) -> bytes:
    """Generate client acquisition analysis report"""
    doc = Document()
    _doc_setup(doc)

    _doc_title(
        doc,
        "CLIENT ACQUISITION REPORT",
        f"Generated: {datetime.now().strftime('%B %d, %Y')}"
    )

    # Summary stats
    h = doc.add_heading("SUMMARY", level=1)
    _style_heading(h)
    won = [c for c in clients if c.get("stage") == "Won"]
    lost = [c for c in clients if c.get("stage") == "Lost"]
    win_rate = (
        f"{round(len(won) / (len(won) + len(lost)) * 100)}%"
        if (len(won) + len(lost)) > 0 else "N/A"
    )
    _add_table(doc,
        ["Metric", "Value"],
        [
            ["Total Clients", str(len(clients))],
            ["Won", str(len(won))],
            ["Lost", str(len(lost))],
            ["Win Rate", win_rate],
            ["High Priority",
             str(sum(
                 1 for c in clients
                 if c.get("priority") == "High"
             ))]
        ]
    )

    # By priority
    h = doc.add_heading("CLIENTS BY PRIORITY", level=1)
    _style_heading(h)
    for priority in ("High", "Medium", "Low"):
        pri_clients = [
            c for c in clients
            if c.get("priority") == priority
        ]
        sub = doc.add_heading(
            f"{priority} Priority ({len(pri_clients)})",
            level=2
        )
        for run in sub.runs:
            run.font.color.rgb = MUTED
        _add_table(doc,
            ["Name", "Company", "Service", "Stage"],
            [
                [
                    c.get("name", ""),
                    c.get("company", ""),
                    c.get("service", ""),
                    c.get("stage", "")
                ]
                for c in pri_clients
            ]
        )

    # By service
    h = doc.add_heading("CLIENTS BY SERVICE", level=1)
    _style_heading(h)
    services: dict = {}
    for c in clients:
        svc = c.get("service") or "Unspecified"
        services[svc] = services.get(svc, 0) + 1

    _add_table(doc,
        ["Service", "Count", "%"],
        sorted(
            [
                [
                    s,
                    str(cnt),
                    f"{round(cnt / len(clients) * 100)}%"
                    if clients else "0%"
                ]
                for s, cnt in services.items()
            ],
            key=lambda x: int(x[1]),
            reverse=True
        )
    )

    # Full client list
    h = doc.add_heading("ALL CLIENTS", level=1)
    _style_heading(h)
    _add_table(doc,
        ["ID", "Name", "Company",
         "Priority", "Stage", "Created"],
        [
            [
                c.get("client_id", ""),
                c.get("name", ""),
                c.get("company", ""),
                c.get("priority", ""),
                c.get("stage", ""),
                str(c.get("created_at", ""))[:10]
            ]
            for c in clients
        ]
    )

    _doc_footer(doc)
    logger.info("Acquisition report generated")
    return _to_bytes(doc)


def generate_agent_activity_report(
    activities: List[dict],
    agent_logs: List[dict]
) -> bytes:
    """Generate agent activity report"""
    doc = Document()
    _doc_setup(doc)

    _doc_title(
        doc,
        "AGENT ACTIVITY REPORT",
        f"Generated: {datetime.now().strftime('%B %d, %Y')}"
    )

    # Summary
    h = doc.add_heading("SUMMARY", level=1)
    _style_heading(h)
    total_acts = len(activities)
    success = sum(
        1 for a in activities
        if a.get("result") == "SUCCESS"
    )
    failed = total_acts - success
    success_rate = (
        f"{round(success / total_acts * 100)}%"
        if total_acts > 0 else "N/A"
    )

    _add_table(doc,
        ["Metric", "Value"],
        [
            ["Total CRM Activities", str(total_acts)],
            ["Successful", str(success)],
            ["Failed", str(failed)],
            ["Success Rate", success_rate],
            ["Total AI Operations", str(len(agent_logs))]
        ]
    )

    # Activity type breakdown
    h = doc.add_heading("ACTIVITY TYPES", level=1)
    _style_heading(h)
    act_types: dict = {}
    for a in activities:
        t = a.get("type", "UNKNOWN")
        act_types[t] = act_types.get(t, 0) + 1

    _add_table(doc,
        ["Activity Type", "Count"],
        sorted(
            [[t, str(c)] for t, c in act_types.items()],
            key=lambda x: int(x[1]),
            reverse=True
        )
    )

    # Activity log
    h = doc.add_heading("ACTIVITY LOG", level=1)
    _style_heading(h)
    _add_table(doc,
        ["Timestamp", "Client", "Type", "Result"],
        [
            [
                str(a.get("timestamp", ""))[:16],
                a.get("client_id", ""),
                a.get("type", ""),
                a.get("result", "")
            ]
            for a in activities[:50]
        ]
    )

    # AI operations log
    h = doc.add_heading("AI OPERATIONS LOG", level=1)
    _style_heading(h)
    _add_table(doc,
        ["Timestamp", "Type", "Input Preview"],
        [
            [
                str(log.get("Timestamp", ""))[:16],
                log.get("Type", ""),
                str(log.get("Input", ""))[:60]
            ]
            for log in agent_logs[:50]
        ]
    )

    _doc_footer(doc)
    logger.info("Agent activity report generated")
    return _to_bytes(doc)